Company_Data=read.csv(file.choose())
View(Company_Data)
str(Company_Data)
summary(Company_Data)
library(moments)
skewness(Company_Data$Sales)
kurtosis(Company_Data$Sales)
hist(Company_Data$Sales)
plot(density(Company_Data$Sales))
sales_category=as.data.frame(ifelse(Company_Data$Sales>10,"High","Low"))
New_data=cbind(Company_Data,sales_category)
library(plyr)
names(New_data)
New_data=rename(New_data,c('ifelse(Company_Data$Sales > 10, \"High\", \"Low\")'='Sales_category'))
nrow(New_data)*0.7
New_data$ShelveLoc=as.factor(New_data$ShelveLoc)
New_data$Urban=as.factor(New_data$Urban)
New_data$US=as.factor(New_data$US)
New_data$Sales_category=as.factor(New_data$Sales_category)
New_data=New_data[,-1]
Train_data=New_data[1:280,]
Test_data=New_data[281:400,]
str(Train_data)
library(randomForest)
Model_fit=randomForest(Train_data$Sales_category~.,data = Train_data,importance=TRUE)
Train_pred=as.data.frame(predict(Model_fit,data=Train_data))
table(Train_pred)
plot(Model_fit,lwd=2)
legend("topright",colnames(Model_fit$err.rate),col = 1:3,cex=0.8,fill = 1:3)
library(gmodels)
CrossTable(Train_data$Sales_category,Train_pred$`predict(Model_fit, data = Train_data)`)
library(caret)
confusionMatrix(Train_pred$`predict(Model_fit, data = Train_data)`,Train_data$Sales_category)
#Accuracy=86.43%
Test_pred=as.data.frame(predict(Model_fit,newdata = Test_data))
table(Test_pred)
CrossTable(Test_data$Sales_category,Test_pred$`predict(Model_fit, newdata = Test_data)`)
confusionMatrix(Test_data$Sales_category,Test_pred$`predict(Model_fit, newdata = Test_data)`)
#Accuracy=86.67%