Fraud_data=read.csv(file.choose())
View(Fraud_data)
str(Fraud_data)
summary(Fraud_data)
library(moments)
skewness(Fraud_data$Taxable.Income)
kurtosis(Fraud_data$Taxable.Income)
hist(Fraud_data$Taxable.Income)
library(lattice)
densityplot(Fraud_data$Taxable.Income)
Tax_income=as.data.frame(ifelse(Fraud_data$Taxable.Income>30000,"Good","Risky"))
New_data=cbind(Fraud_data,Tax_income)
str(New_data)
New_data$Undergrad=as.factor(New_data$Undergrad)
New_data$Marital.Status=as.factor(New_data$Marital.Status)
New_data$Urban=as.factor(New_data$Urban)
library(plyr)
names(New_data)
New_data=rename(New_data,c('ifelse(Fraud_data$Taxable.Income > 30000, \"Good\", \"Risky\")'='Tax_inc'))
New_data$Tax_inc=as.factor(New_data$Tax_inc)
New_data=New_data[,-3]
nrow(New_data)*0.75
Train_data=New_data[1:450,]
Test_data=New_data[451:600,]
library(randomForest)
Model_train=randomForest(Train_data$Tax_inc~.,data = Train_data,importance=TRUE)
plot(Model_train)
legend("topright",colnames(Model_train$err.rate),col=1:3,cex=0.8,fill = 1:3)
summary(Model_train)
pred_train=as.data.frame(predict(Model_train,data=Train_data))
table(pred_train)
library(gmodels)
CrossTable(Train_data$Tax_inc,pred_train$`predict(Model_train, data = Train_data)`)
library(caret)
confusionMatrix(Train_data$Tax_inc,pred_train$`predict(Model_train, data = Train_data)`)
#Accuracy = 77.48%
pred_test=as.data.frame(predict(Model_train,newdata = Test_data))
table(pred_test)
CrossTable(Test_data$Tax_inc,pred_test$`predict(Model_train, newdata = Test_data)`)
confusionMatrix(Test_data$Tax_inc,pred_test$`predict(Model_train, newdata = Test_data)`)
# Accuracy : 82%